<?php
declare(strict_types=1);

namespace App\Shop\Actions;


use App\Shop\Entity\Product;
use App\Shop\Repository\ProductRepository;
use Framework\Actions\CrudAction;
use Framework\Database\ORM\EntityRepository;
use Framework\Routing\Router;
use Framework\Session\FlashService;
use Framework\Templating\Renderer\RendererInterface;
use Framework\Validation\Validator;
use Psr\Http\Message\ServerRequestInterface;

/**
 * Created by PhpStorm at 10.12.2023
 *
 * @AdminProductAction
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package App\Shop\Actions
 */
class AdminProductAction extends CrudAction
{


       /**
        * @var string
       */
       protected string $viewPath    = "@shop/admin/products";


       /**
        * @var string
       */
       protected string $routePrefix = 'shop.admin.products';



       protected $acceptedParams = [
           'name', 'slug', 'created_at', 'description', 'price'
       ];


        /**
         * @param RendererInterface $renderer
         * @param Router $router
         * @param ProductRepository $repository
         * @param FlashService $flash
        */
       public function __construct(
           RendererInterface $renderer,
           Router $router,
           ProductRepository $repository,
           FlashService $flash
       )
       {
           parent::__construct($renderer, $router, $repository, $flash);
       }



       protected function getNewEntity(): Product
       {
           /** @var Product $entity */
           $entity = parent::getNewEntity();
           $entity->setCreatedAt(new \DateTime());
           return $entity;
       }


    /**
     * @param ServerRequestInterface $request
     * @return Validator
     */
     protected function getValidator(ServerRequestInterface $request): Validator
     {
         $validator =  parent::getValidator($request);
         $validator->required($this->acceptedParams)
                   ->length('name', 5)
                   ->length('slug', 5)
                   ->slug('slug')
                   ->unique('slug', $this->repository, null, (int)$request->getAttribute('id'))
                   ->length('description', 5)
                   ->numeric('price')
                   ->dateTime('created_at')
                   ->extension('image', ['jpg', 'png']);

         if ($request->getAttribute('id') === null) {
              $validator->uploaded('image');
         }

         return $validator;
     }


     /*
     public function edit(ServerRequestInterface $request): mixed
     {
         $price = $request->getAttribute('price');
         $request->withAttribute('price', (float)$price);
         return parent::edit($request); // TODO: Change the autogenerated stub
     }
     */
}