<?php

use App\Entity\Product;
use Grafikart\Routing\Router;
use Grafikart\Service\Currency\Currency;

/** @var Product[] $products */
/** @var Router $router */
?>
<div class="checkout">
    <div class="title mt-3">
        <h2 class="first">Shopping Cart</h2>
        <a href="#" class="proceed">
            Proceed to checkout
        </a>
    </div>
    <table class="table table-striped mt-3">
        <thead>
        <tr>
            <th class="name">Product name</th>
            <th class="price">Price</th>
            <th class="quantity">Quantity</th>
            <th class="subtotal">Prix avec TVA</th>
            <th class="action">Actions</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product): ?>
                <tr>
                    <td>
                        <a href="#" class="img">
                            <img src="<?= $product->getImagePath() ?>" alt="Card image cap" width="100">
                            <span class="name"><?= $product->getName() ?></span>
                        </a>
                    </td>
                    <td>
                        <span class="price">
                            <?= $product->getFormatPrice() ?> <?= Currency::euro() ?>
                        </span>
                    </td>
                    <td>
                        <span class="quantity">1</span>
                    </td>
                    <td>
                        <span class="subtotal">
                            <?= $product->getFormatPrice(1.196) ?> <?= Currency::euro() ?>
                        </span>
                    </td>
                    <td>
                        <a href="<?= $router->generate('cart.delete', ['id' => $product->getId()]) ?>" class="text-danger">
                            Supprimer
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="row-total">
        Grand total: <span class="total">2640.18 <?= Currency::euro() ?></span>
    </div>
</div>