<div class="container__home">
    <h1>Mon portfolio en PHP!</h1>
    <div class="row">
        <?php foreach ($works as $work): ?>
          <div class="col-sm-3">
              <a href="<?= $router->generate('portfolio.show', ['id' => $work->getId() ]) ?>">
                  <img src="/uploads/works/<?= $work->getImageName() ?>" alt="">
                  <h2><?= $work->getName() ?></h2>
                  <?= $work->getResizedImage(150, 150) ?>
              </a>
          </div>
        <?php endforeach; ?>
    </div>
</div>