<div class="form-group">
    <?= $form->text('name', [
        'label' => "Nom de la realisation",
        'attrs' => [
            'class' => 'form-control'
        ]
    ]) ?>
</div>
<div class="form-group">
    <?= $form->text('slug', [
        'label' => "URL de la realisation",
        'attrs' => [
            'class' => 'form-control'
        ]
    ]) ?>
</div>

<!-- http://fillerama.io/ -->
<div class="form-group">
    <?= $form->textarea('content', [
        'label' => "Contenu de la realisation",
        'attrs' => [
            'class' => 'form-control',
            'style' => 'border: 1px solid #ccc;', # just one test
        ]
    ]) ?>
</div>

<div class="form-group">
    <?= $form->select('category_id', [
        'label' => "Categorie",
        'options' => $categories,
        'attrs' => [
            'class' => 'form-control'
        ]
    ]) ?>
</div>

