<!--
https://www.tiny.cloud/
http://fillerama.io/
-->
<div class="form-group">
    <?= $form->text('name', [
        'label' => "Nom de la realisation",
        'attrs' => [
            'class' => 'form-control'
        ]
    ]) ?>
</div>
<div class="form-group">
    <?= $form->text('slug', [
        'label' => "URL de la realisation",
        'attrs' => [
            'class' => 'form-control'
        ]
    ]) ?>
</div>

<div class="form-group">
    <?= $form->textarea('content', [
        'label' => "Contenu de la realisation",
        'attrs' => [
            'id'    => 'tiny',
            'class' => 'form-control',
            'style' => 'border: 1px solid #ccc;', # just one test
        ]
    ]) ?>
</div>

<div class="form-group">
    <?= $form->select('category_id', [
        'label' => "Categorie",
        'options' => $categories,
        'attrs' => [
            'class' => 'form-control'
        ]
    ]) ?>
</div>

<div class="form-group">
    <?= $form->input('file', 'images[]', [
        'label' => "Upload Image",
        'attrs' => [
            'id'    => 'work_image__id',
            'class' => 'form-control'
        ]
    ]) ?>
    <?= $form->input('file', 'images[]', [
        'label' => false,
        'attrs' => [
            'class' => 'hidden form-control',
            'id'    => 'duplicate'
        ]
    ]) ?>
</div>
<p>
    <a href="#" class="btn btn-success" id="duplicate_btn">Ajouter une image</a>
</p>

