<h1>Editer une realisation</h1>
<form
        action="<?= $router->generate('admin.work.update', ['id' => $work->getId()]) ?>"
        method="POST"
        enctype="multipart/form-data"
>
    <div class="row">
        <div class="col-sm-8">
            <input type="hidden" name="_csrf" value="<?= $csrfToken ?>">
            <input type="hidden" name="_method" value="PUT">
            <?php include '_form.phtml' ?>
        </div>
        <div class="col-sm-4">
            <?php if (!empty($images)): ?>
                <?php foreach ($images as $k => $image): ?>
                        <img src="<?= "/uploads/works/{$image->getName()}" ?>" width="100"">
                        <a href="<?= $router->generate('admin.work.image.delete', ['id' => $image->getId(), 'csrf' => $csrfToken, 'work' => $work->getId() ]) ?>"
                           onclick="return confirm('Voulez-vous supprimer ?')"
                           title="Clickez pour la suppression"
                        >Supprimer</a> |
                        <a href="<?= $router->generate('admin.work.image.highlight', ['id' => $image->getId(), 'csrf' => $csrfToken, 'work' => $work->getId() ]) ?>"
                           onclick="return confirm('Voulez-vous mettre en ligne ?')"
                           title="Clickez pour mettre en avant"
                        >Mettre a la une</a>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="form-group mt-3">
                <?= $form->input('file', 'images[]', [
                    'label' => "Telecharger",
                    'attrs' => [
                        'id'    => 'work_image__id',
                        'class' => 'form-control'
                    ]
                ]) ?>
                <?= $form->input('file', 'images[]', [
                    'label' => false,
                    'attrs' => [
                        'class' => 'hidden form-control',
                        'id'    => 'duplicate'
                    ]
                ]) ?>
            </div>
            <p>
                <a href="#" class="btn btn-success" id="duplicate_btn">Ajouter une image</a>
            </p>
        </div>
        <button class="btn btn-primary" type="submit">Enregister</button>
    </div>
</form>