<h1>Editer une realisation</h1>
<div class="row">
    <div class="col-sm-8">
        <form
                action="<?= $router->generate('admin.work.update', ['id' => $work->getId()]) ?>"
                method="POST"
                enctype="multipart/form-data"
        >
            <input type="hidden" name="_csrf" value="<?= $csrfToken ?>">
            <input type="hidden" name="_method" value="PUT">
            <?php include '_form.phtml' ?>
            <button class="btn btn-primary" type="submit">Enregister</button>
        </form>
    </div>
    <div class="col-sm-4">
        <?php foreach ($images as $k => $image): ?>
            <a href="<?= $router->generate('admin.work.image.delete', ['id' => $image->getId(), 'csrf' => $csrfToken, 'work' => $work->getId() ]) ?>"
               onclick="return confirm('Voulez-vous supprimer ?')"
               title="Clickez sur l'image pour la suppression"
            >
                <img src="<?= "/uploads/works/{$image->getName()}" ?>" width="100" alt="<?= $image->getName() ?>">
            </a>
        <?php endforeach; ?>
    </div>
</div>