<div class="container__works">
    <h1>Mes realisations</h1>
    <p>
        <a href="<?= $router->generate('admin.work.create') ?>" class="btn btn-success">
            Ajouter une nouvelle realisation
        </a>
    </p>
    <table class="table table-striped">
        <thead>
           <tr>
               <th>ID</th>
               <th>Nom</th>
               <th>Actions</th>
           </tr>
        </thead>
        <tbdy>
            <?php foreach ($works as $work): ?>
               <tr>
                   <td><?= $work->getId() ?></td>
                   <td><?= $work->getName() ?></td>
                   <td>
                       <a href="<?= $router->generate('admin.work.edit', ['id' => $work->getId()]) ?>" class="btn btn-default">
                           Editer
                       </a>
                       <?php include '_delete.phtml'?>
                   </td>
               </tr>
            <?php endforeach; ?>
        </tbdy>
    </table>
</div>