<div class="form-group">
    <label for="title">Title</label>
    <input type="text" name="title" value="PHP Level6 New" id="title" class="form-control">
</div>
<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description" id="description" class="form-control">something about php level6 new</textarea>
</div>
<div class="form-group">
    <label for="author">Author</label>
    <select name="author" id="author" class="form-control">
        <option value="John B">John brown</option>
        <option value="Martin L">Martin L</option>
        <option value="Harry W">Harry W</option>
    </select>
</div>
<div class="form-group">
    <label for="price">Price</label>
    <input name="price" id="price" type="number" class="form-control" value="35">
</div>