<?php
use Grafikart\Service\Calendar\Calendar;
use Grafikart\Utils\Str;

/** @var $calendar Calendar */
/** @var $year string */
?>

<div class="periods">
    <h2 class="year text-danger">
        <?= $calendar->getCurrentYear() ?>
    </h2>
    <div class="months">
        <nav class="navbar navbar-expand-lg navbar-light bg-light months-navbar">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                   <?php foreach ($calendar->getMonths() as $id => $month): ?>
                       <li class="nav-item month-item">
                           <a class="nav-link month-link" href="#" id="month-link-<?= ($id + 1) ?>">
                               <?= Str::sub($month, 0, 3) ?>
                           </a>
                       </li>
                   <?php endforeach; ?>
                </ul>
            </div>
        </nav>
        <div>
            <pre><?php //print_r($calendar->getCurrentDates()); ?></pre>
            <?php foreach ($calendar->getCurrentDates() as $monthNumber => $days): ?>
              <div class="month relative" id="month-<?= $monthNumber ?>">
                  <table class="table table-striped">
                      <thead>
                          <tr>
                             <?php foreach ($calendar->getDays() as $day): ?>
                                 <th scope="col"><?= Str::sub($day, 0, 3) ?></th>
                             <?php endforeach; ?>
                          </tr>
                      </thead>
                      <tbody>
                        <tr>
                            <?php $end = end($days); foreach ($days as $day => $week): ?>
                              <?php $time = Str::toTime("$year-$month-$day"); ?>
                              <?php if ($day == 1): ?>
                                  <td colspan="<?= ($week - 1) ?>" class="padding"></td>
                              <?php endif; ?>
                              <td>
                                  <div class="relative">
                                      <div class="day">
                                          <?= $day ?>
                                      </div>
                                  </div>
                                  <ul class="events">
                                      <?php if(isset($events[$time])): ?>
                                      <?php endif; ?>
                                  </ul>
                              </td>
                              <?php if ($week == 7): ?>
                                </tr><tr>
                              <?php endif; ?>
                            <?php endforeach; ?>
                            <?php if ($end != 7): ?>
                                <td colspan="<?= (7 - $end) ?>" class="padding"></td>
                            <?php endif; ?>
                        </tr>
                      </tbody>
                  </table>
              </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php include 'debug/info.phtml'; ?>