<hr>
<ul class="nav">
    <li class="nav-item"><a class="nav-link active" href="#">All categories</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Electronics</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Fashion</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Entertainment</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Motors</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Outdoors</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Gift</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Jewelry</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Shoes</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Computers</a></li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
    </li>
</ul>
<hr>
<div class="breadcrumb">
    <small>You are right here : Home &gt;&gt; <a href="#">Electronics</a></small>
</div>