<?php

use Grafikart\Service\Currency\Currency;
use Grafikart\Templating\Renderer;

/** @var string $viewPath */
/** @var Renderer $renderer */
?>
<section>
   <div class="container">
       <h1>Products</h1>
       <div class="row">
           <div class="col-sm-4">
               <div class="card" style="width: 18rem;">
                   <a href="#">
                       <img class="card-img-top" src="https://placehold.co/150x150" alt="Card image cap">
                   </a>
                   <div class="card-body">
                       <div class="description">
                           Apple, <strong>Ipad :</strong>
                           <a href="#" class="price">1500,00 <?= Currency::euro() ?></a>
                       </div>
                       <a href="#" class="gift">Gift</a>
                       <div class="rating">
                           <span>Rating :</span>
                       </div>
                       <ul>
                           <li><a href="#">1</a></li>
                           <li><a href="#">2</a></li>
                           <li><a href="#">3</a></li>
                           <li><a href="#">4</a></li>
                           <li><a href="#" class="off">5</a></li>
                       </ul>
                       <!--
                       <h5 class="card-title">Card title</h5>
                       <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                       <a href="#" class="btn btn-primary">Go somewhere</a>
                       -->
                       <a href="#" class="btn btn-success add">add</a>
                   </div>
               </div>
           </div>
       </div>
   </div>
</section>
<hr>
<?php $renderer->includePath('/partials/pagination'); ?>