<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mon administration</title>
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-dark bg-dark" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a href="<?= $router->generate('home') ?>" class="navbar-brand">Mon premier portfolio en PHP</a>
        </div>
        <ul class="nav navbar-nav">
            <li>
                <a href="<?= $router->generate('admin.category.list') ?>">Categories</a>
            </li>
        </ul>
    </div><!-- /.container -->
</nav><!-- /.navbar -->

<div class="container">

    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>

    <div class="block__flash">
        <?php if ($session->hasFlashes()): ?>
            <?php foreach ($session->getFlashes() as $key => $message): ?>
                <div class="alert alert-<?= $key ?>">
                    <?= $message ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    {{ content }}

    <?php include 'debug/info.phtml' ?>

</div><!-- /.container -->

<!-- Bootstrap core Javascript
=========================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>
</html>