<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mon administration</title>
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/app.css">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container">
        <a href="<?= $router->generate('home') ?>" class="navbar-brand">Mon premier portfolio en PHP</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="<?= $router->generate('admin.category.list') ?>" class="nav-link">Categories</a>
            </li>
            <li class="nav-item">
                <a href="<?= $router->generate('admin.work.list') ?>" class="nav-link">Realisations</a>
            </li>
        </ul>
    </div><!-- /.container -->
</nav><!-- /.navbar -->

<div class="container">

    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>

    <div class="block__flash">
        <?php if ($session->hasFlashes()): ?>
            <?php foreach ($session->getFlashes() as $key => $message): ?>
                <div class="alert alert-<?= $key ?>">
                    <?= $message ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    {{ content }}

    <?php include 'debug/info.phtml' ?>

</div><!-- /.container -->

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script src="https://cdn.jsdelivr.net/npm/@tinymce/tinymce-jquery@1/dist/tinymce-jquery.min.js"></script>
<script src="/assets/tinymce/js/custom.js"></script>
<script src="/assets/js/app.js"></script>
<!-- Bootstrap core Javascript
=========================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>
</html>