<div class="row">
    <div class="col-sm-4">
        <h2>SERVER</h2>
        <pre>
            <?php print_r($_SERVER); ?>
        </pre>
    </div>
    <div class="col-sm-4">
        <h2>CONSTANTE</h2>
        <pre><?php print_r(get_defined_constants()); ?></pre>
        <pre><?php // print_r(get_defined_functions()); ?></pre>
        <pre><?php // print_r(get_defined_vars()); ?></pre>
    </div>
    <div class="col-sm-4">
        <h2>SESSION</h2>
        <pre><?php print_r($_SESSION); ?></pre>
    </div>
</div>