<?php

use Grafikart\Routing\Router;
use Grafikart\Service\Currency\Currency;

/** @var $router Router */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ecommerce template</title>
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/shopping.css">
</head>
<body>
<nav class="navbar navbar-dark bg-dark" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a href="<?= $router->generate('shopping.home') ?>" class="navbar-brand logo">
                Shopping
            </a>
        </div>
        <ul class="navbar-nav basket"><!-- basket (panier) -->
            <li class="nav-item items">
                <a href="<?= $router->generate('shopping.cart.list') ?>" class="nav-link">
                    Cart <span class="badge">0</span>
                </a>
            </li>
            <li class="nav-item total">
               TOTAL <span>1320.09 <?= Currency::euro() ?></span>
            </li>
        </ul>
    </div><!-- /.container -->
</nav><!-- /.navbar -->

<section class="subheader">
    <div class="container mt-3">
        <h2>Welcome visitor you can <a href="#">log in</a> or <a href="#">create an account</a></h2>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                {{ content }}
            </div>
            <div class="col-sm-4">
                <ul class="wrap">
                    <li><a href="#">All categories</a></li>
                    <li><a href="#">Electronics</a></li>
                    <li><a href="#">Fashion</a></li>
                    <li><a href="#">Entertainment</a></li>
                    <li><a href="#">Motors</a></li>
                    <li><a href="#">Outdoors</a></li>
                    <li><a href="#">Gift</a></li>
                    <li><a href="#">Jewelry</a></li>
                    <li><a href="#">Shoes</a></li>
                    <li><a href="#">Computers</a></li>
                </ul>
            </div>
        </div>
    </div><!-- /.container -->
</section>

<!--
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="application/javascript"></script>
-->
<script src="/assets/js/jquery/jquery.min.js"></script>
<script src="/assets/js/shopping.js"></script>
<!-- Bootstrap core Javascript
=========================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>
</html>